/*
 * generated by Xtext 2.14.0
 */
package fr.ubo.collector.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
}
