/**
 * generated by Xtext 2.14.0
 */
package fr.ubo.collector.dsl;

import fr.ubo.collector.dsl.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
