/**
 * generated by Xtext 2.14.0
 */
package fr.ubo.collector.dsl.scoping;

import fr.ubo.collector.dsl.scoping.AbstractDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DslScopeProvider extends AbstractDslScopeProvider {
}
