/*
 * generated by Xtext 2.14.0
 */
package fr.ubo.collector.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/ubo/collector/dsl/parser/antlr/internal/InternalDsl.tokens");
	}
}
