/**
 * generated by Xtext 2.14.0
 */
package fr.ubo.collector.dsl.ui.contentassist;

import fr.ubo.collector.dsl.ui.contentassist.AbstractDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DslProposalProvider extends AbstractDslProposalProvider {
}
