/*
 * generated by Xtext 2.14.0
 */
package fr.ubo.collector.dsl.ide

import com.google.inject.Guice
import fr.ubo.collector.dsl.DslRuntimeModule
import fr.ubo.collector.dsl.DslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DslIdeSetup extends DslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DslRuntimeModule, new DslIdeModule))
	}
	
}
